//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testtoken
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int IdUsuario { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Logueado { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> FechaUltIngreso { get; set; }
    }
}
